# Name of the experiment for saving files
experiment_name: test_delete
save_folder: results/

# Define training strategy
training_strategy:
  niter: 50 # of iter at starting learning rate. Total #epochs is niter + niter_decay'
  niter_decay: 0 # of iter to linearly decay learning rate to zero
  is_train: True
  class_weight: True
  class_weight_cityscapes: False

# model options
model:
  architecture: vgg16 #[options: 'vgg16', 'vgg16_bn', 'vgg16_guided', 'resnet18', 'vgg16_correlated']
  semantic: True
  pretrained: True
  correlation: True
  spade: '' #[options: 'encoder', 'decoder', 'both', '']
  num_semantic_classes: 19 # Actual training labels

# logger options
logger:
  results_dir: ./data_analysis
  save_epoch_freq: 50 #frequency of saving checkpoints at the end of epochs

# loss options (remove tasks not needed)
loss:  CrossEntropyLoss

# optimization options
optimizer:
  algorithm: Adam # ['Adam' or 'SGD']
  # Define accordingly, e.g.
  parameters:
    lr: 1.e-5 # 1.e-4
    lr_policy: ReduceLROnPlateau
    patience: 3
    factor: 0.75
    weight_decay: 0.0000
    beta1: 0.5 # momentum term of adam
    beta2: 0.999 # momentum term of adam

# parameters for dataloaders
train_dataloader:
  dataset_args:
    dataroot: /home/giancarlo/data/innosuisse/epfl/train
    #dataroot: /media/giancarlo/Samsung_T5/master_thesis/data/road_anomaly # (for workstation debugging)
    #dataroot: /home/giancarlo/data/innosuisse/road_anomaly  #(only for quick debugging)
    preprocess_mode: none
    crop_size: 512
    aspect_ratio: 2
    void: True
    num_semantic_classes: 19
    is_train: True
  dataloader_args:
    batch_size: 8
    num_workers: 4
    shuffle: True
val_dataloader:
  dataset_args:
    dataroot: /home/giancarlo/data/innosuisse/fs_lost_and_found
    #dataroot: /media/giancarlo/Samsung_T5/master_thesis/data/fs_lost_and_found # (for workstation debugging)
    preprocess_mode: none
    crop_size: 512
    aspect_ratio: 2
    num_semantic_classes: 19
    is_train: False
  dataloader_args:
    batch_size: 1
    num_workers: 1
    shuffle: False
test_dataloader1:
  dataset_args:
    dataroot: /home/giancarlo/data/innosuisse/road_anomaly
    #dataroot: /media/giancarlo/Samsung_T5/master_thesis/data/road_anomaly #(for workstation debugging)
    preprocess_mode: none
    crop_size: 512
    aspect_ratio: 2
    roi: False
    num_semantic_classes: 19
    is_train: False
  dataloader_args:
    batch_size: 1
    num_workers: 1
    shuffle: False
test_dataloader2:
  dataset_args:
    dataroot: /home/giancarlo/data/innosuisse/fs_static
    #dataroot: /media/giancarlo/Samsung_T5/master_thesis/data/fs_static # (for workstation debugging)
    preprocess_mode: none
    crop_size: 512
    aspect_ratio: 2
    roi: True
    num_semantic_classes: 19
    is_train: False
  dataloader_args:
    batch_size: 1
    num_workers: 1
    shuffle: False
test_dataloader3:
  dataset_args:
    dataroot: /home/giancarlo/data/innosuisse/fs_lost_and_found
    #dataroot: /media/giancarlo/Samsung_T5/master_thesis/data/fs_lost_and_found # (for workstation debugging)
    preprocess_mode: none
    crop_size: 512
    aspect_ratio: 2
    roi: True
    num_semantic_classes: 19
    is_train: False
  dataloader_args:
    batch_size: 1
    num_workers: 1
    shuffle: False
img_dataloader:
  dataset_args:
    dataroot: /home/giancarlo/data/innosuisse/visualization_imgs
    preprocess_mode: none
    crop_size: 512
    aspect_ratio: 2
    void: True
    num_semantic_classes: 19
    is_train: True
  dataloader_args:
    batch_size: 8
    num_workers: 4
    shuffle: False
