# Name of the experiment for saving files
experiment_name: final_baseline_2
save_folder: results/

# Define training strategy
training_strategy:
  niter: 50 # of iter at starting learning rate. Total #epochs is niter + niter_decay'
  niter_decay: 0 # of iter to linearly decay learning rate to zero
  is_train: True
  class_weight: True
  class_weight_cityscapes: False

# model options
model:
  architecture: vgg16 #[options: 'vgg16']
  # Define accordingly, e.g.
  parameters:
    pretrained: True
    correlation: True

# logger options
logger:
  results_dir: ./logs
  save_epoch_freq: 1 #frequency of saving checkpoints at the end of epochs

# loss options (remove tasks not needed)
loss:  CrossEntropyLoss

# optimization options
optimizer:
  algorithm: Adam # ['Adam' or 'SGD']
  # Define accordingly, e.g.
  parameters:
    lr: 1.e-4 # 1.e-4
    weight_decay: 0.0000
    beta1: 0.5 # momentum term of adam
    beta2: 0.999 # momentum term of adam

# learning rate scheduler options
scheduler:
  lr_policy: PolynomialLR
  # Define accordingly, e.g.
  parameters:
    max_iter: 300000
    decay_iter: 1
    gamma: 0.9

# parameters for dataset
dataset:
  num_classes: 19 # Actual training labels

# parameters for dataloaders
train_dataloader:
  dataset_args:
    dataroot: /home/giancarlo/data/innosuisse/epfl/train
    #dataroot: /home/giancarlo/data/innosuisse/road_anomaly (only for quick debugging)
    preprocess_mode: fixed
    load_size: 1024
    crop_size: 1024
    aspect_ratio: 2
    image_set: train
    no_flip: false
  dataloader_args:
    batch_size: 4
    num_workers: 2
    shuffle: True
val_dataloader:
  dataset_args:
    dataroot: /home/giancarlo/data/innosuisse/fs_lost_and_found
    preprocess_mode: fixed
    load_size: 1024
    crop_size: 1024
    aspect_ratio: 2
    image_set: val
    no_flip: True
  dataloader_args:
    batch_size: 1
    num_workers: 1
    shuffle: False
test_dataloader1:
  dataset_args:
    dataroot: /home/giancarlo/data/innosuisse/road_anomaly
    preprocess_mode: fixed
    load_size: 1024
    crop_size: 1024
    aspect_ratio: 2
    image_set: test
    no_flip: True
    roi: False
  dataloader_args:
    batch_size: 1
    num_workers: 1
    shuffle: False
test_dataloader2:
  dataset_args:
    dataroot: /home/giancarlo/data/innosuisse/fs_static
    preprocess_mode: fixed
    load_size: 1024
    crop_size: 1024
    aspect_ratio: 2
    image_set: test
    no_flip: True
    roi: True
  dataloader_args:
    batch_size: 1
    num_workers: 1
    shuffle: False
test_dataloader3:
  dataset_args:
    dataroot: /home/giancarlo/data/innosuisse/fs_lost_and_found
    preprocess_mode: fixed
    load_size: 1024
    crop_size: 1024
    aspect_ratio: 2
    image_set: test
    no_flip: True
    roi: True
  dataloader_args:
    batch_size: 1
    num_workers: 1
    shuffle: False